version: '3.8'

services:
  web:
    build: .
    container_name: health-prediction-app
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./trained_models:/app/trained_models
      - ./model_results:/app/model_results
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1G
